# Generated by Django 5.0.3 on 2024-04-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('work_program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('work_program_id', models.ForeignKey(db_column='work_program_id', on_delete=django.db.models.deletion.CASCADE, to='summarize_app_api.description')),
            ],
        ),
        migrations.CreateModel(
            name='Summary_text',
            fields=[
                ('summarization_id', models.AutoField(primary_key=True, serialize=False)),
                ('summarize_text', models.TextField()),
                ('wp_id', models.ForeignKey(db_column='wp_id', on_delete=django.db.models.deletion.CASCADE, to='summarize_app_api.description')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_score', models.BooleanField()),
                ('comment_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('summarization_id', models.ForeignKey(db_column='summarization_id', on_delete=django.db.models.deletion.CASCADE, to='summarize_app_api.summary_text')),
            ],
        ),
    ]
