# Generated by Django 4.2.11 on 2024-03-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('work_program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarization_id', models.CharField(max_length=100)),
                ('summirize_text', models.TimeField()),
                ('work_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize_app.description')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_score', models.BooleanField()),
                ('comment_text', models.TimeField()),
                ('author', models.CharField(max_length=100)),
                ('summarization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize_app.summary_text')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('work_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize_app.description')),
            ],
        ),
    ]
