# Generated by Django 5.0.3 on 2024-03-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize_app', '0005_alter_summary_text_wp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary_text',
            old_name='summirize_text',
            new_name='summarize_text',
        ),
    ]
