# Generated by Django 5.0.3 on 2024-03-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize_app', '0006_rename_summirize_text_summary_text_summarize_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='summarization_id',
            field=models.ForeignKey(db_column='summarization_id', on_delete=django.db.models.deletion.CASCADE, to='summarize_app.summary_text'),
        ),
    ]
